name = "Neopolitan"
author = "Dakedres"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe41bd3ab2b05ab0b924bfa741944cb41d9e45bb8c7e0cc8f9425c74c4b00675"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3"]
