name = "Neopolitan"
author = "Dakedres"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6265ca12553ed98cafa61973821430a86111cc3d44c644c286ee3d66ecff8cf"

[versions]
forge = "36.2.20"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3"]
