name = "Foxie Farm"
author = "Dakedres"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3628652ff482b6f2c49e1e3691726059178857883c54d5456bde984604a033e9"

[versions]
forge = "36.1.32"
minecraft = "1.16.5"

[options]
acceptable-game-versions = ["1.16.4", "1.16.3"]
