# We just want to hide it
[gui]
	#The x-position of the GUI button
	#Range: -10000 ~ 10000
	buttonX = 10000
	#The y-position of the GUI button
	#Range: -10000 ~ 10000
	buttonY = 10000
	#The main text color for the GUI
	textColor = "4210752"

