
#Here are configs that need reloading to take effect
[initialization]

	[initialization.general]
		#Enable Creative Tab
		creative_tab = false
		#Enables custom Configured config screen
		custom_configured_screen = true
		#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
		dispensers = true
		#Creates a creative tab full of filled jars
		jar_tab = false

	[initialization.entities]
		firefly = false

	[initialization.blocks]
		clock_block = false
		speaker_block = true
		sack = true
		#WIP
		laser_block = false
		bellows = true
		hanging_sign = false
		bomb = true
		#WIP
		amethyst_arrow = true
		cage = true
		stone_tile = true
		blaze_rod = true
		bamboo_spikes = false
		hourglass = true
		raked_gravel = true
		jar = true
		stick = true
		rope_arrow = true
		checker_block = false
		slingshot = true
		wattle_and_daub = true
		stone_lamp = true
		cog_block = true
		crank = true
		copper_lantern = true
		pancake = true
		statue = true
		iron_gate = true
		piston_launcher = true
		netherite_trapdoor = false
		bamboo_spikes_tipped = false
		fodder = true
		globe = false
		sconce = false
		candelabra = true
		timber_frame = false
		safe = true
		sconce_lever = false
		#WIP
		present = false
		sign_post = true
		pedestal = true
		blackboard = true
		netherite_door = false
		candle_holder = false
		flint_block = false
		rope = true
		flags = true
		notice_board = true
		redstone_illuminator = false
		crimson_lantern = false
		lock_block = false
		flax = false
		planter = true
		wind_vane = true
		item_shelf = true
		turn_table = false
		faucet = false
		daub = false
		gold_trapdoor = true
		feather_block = false
		magma_cream_block = false
		goblet = false
		sconce_green = false
		flute = true
		pulley_block = false
		gold_door = true

